const Tonic = require('@conductorlab/tonic')
const components = require('..')

components(Tonic)

require('./src/badge')
require('./src/button')
require('./src/chart')
require('./src/checkbox')
require('./src/dialog')
require('./src/icon')
require('./src/input')
require('./src/panel')
require('./src/popover')
require('./src/progressbar')
require('./src/profileimage')
require('./src/router')
require('./src/select')
require('./src/tabs')
require('./src/textarea')
require('./src/toaster')
require('./src/toasterinline')
require('./src/toggle')
require('./src/tooltip')
require('./src/windowed')
