const components = require('..')
components(require('@optoolco/tonic'), { strict: true })

require('../accordion/test')
require('../router/test')
require('../panel/test')
require('../dialog/test')
require('../tabs/test')
require('../windowed/test')
require('../tooltip/test')
require('../popover/test')
require('../badge/test')
require('../button/test')
require('../chart/test')
require('../checkbox/test')
require('../icon/test')
require('../input/test')
require('../progress-bar/test')
require('../profile-image/test')
require('../range/test')
require('../relative-time/test')
require('../select/test')
require('../textarea/test')
require('../toaster/test')
require('../toaster-inline/test')
require('../toggle/test')
