const Tonic = require('@conductorlab/tonic')
const components = require('../..')

components(Tonic)

require('./badge')
require('./button')
require('./chart')
require('./checkbox')
require('./dialog')
require('./icon')
require('./input')
require('./panel')
require('./popover')
require('./progressbar')
require('./profileimage')
require('./router')
require('./select')
require('./tabs')
require('./textarea')
require('./toaster')
require('./toasterinline')
require('./toggle')
require('./tooltip')
require('./windowed')
